## Project Description

The purpose of Project MOSAIC (NSF DUE-0920350) is to help unify instruction in statistics and calculus, integrating them with modeling and computation.

The work in Summer 2015 has two main objectives:

1. Design and develop error handlers and graphical user interfaces that will help students construct correct commands, warn them when they are not, and suggest changes.
2. Work with faculty from the ACM data-science group and the Consortium for Visualization and Computation to put their research case studies in a form that can readily be used by students. This will include participation in the CVC meeting at Smith College in mid-July, and pre-meeting planning with participants and post-meeting follow-up with them.

The summer's work should familiarize the students with core elements of data science. Technologies that will be used include R, Shiny, GitHub, RMarkdown, and data-science packages such as `dplyr` and `ggplot2`.

## Topics

### A shiny graphics constructor

A good starting point might be <https://roose.shinyapps.io/shinyData/>, with a GitHub repository at <https://github.com/yindeng/shinyData>

Other ideas: 

* <http://www.showmeshiny.com/visualizing-ggplot2/>
* <http://www.showmeshiny.com/ggplot-live/>
* <http://www.showmeshiny.com/ggplot2-theme-builder/>
* <http://www.showmeshiny.com/r-graph-catalog/>
* <https://winston.shinyapps.io/activity-dashboard/>
* <http://www.stat.ucla.edu/~jeroen/ggplot2/>
* shinythemes package?

[Shiny layout guide](http://shiny.rstudio.com/articles/layout-guide.html)

## Swirl interactive lessons

Anything good here?  <https://github.com/swirldev/swirl_courses/tree/master/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr>

### Interact with a database.

### mosaicManip translation

Objective: Create an R package with the `mosaicManip` apps in Shiny format.

* Do the basic translation.
* See if there is a unified control layout paradigm that we can apply to many apps. If we can have a common theme to the layout, things will go much more easily for the user.
* Write a control function that invokes individual apps, e.g.,
    `mosaicApp("trajectory")`

The existing software is in `mosaicApps`.

* `mosaicManipOriginal` were written with the `manipulate` system.
* `mosaicManipShiny` were written with Shiny.

Leave these directories exactly as they are.  Copy out files to create new .R files

The plotting parts of each program are usually the most intricate.  Those can be lifted straight into the new files, then modified if and when needed.
